# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

version: '3.3'

services:
  traefik:
    image: 'traefik:v2.8'
    container_name: 'traefik'
    restart: unless-stopped
    command:
      - '--log.level=INFO'
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - '--api.insecure=true'

      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--certificatesresolvers.myresolver.acme.email=${EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      
    ports:
      - '80:80'
      - '443:443'

    volumes:
      - './volumes/letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  whoami-iamon99:
    image: 'traefik/whoami'
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-iamon99-http.rule=Host(`whoami.iamon99.com`)'
      - 'traefik.http.routers.whoami-iamon99-http.entrypoints=web'
      - 'traefik.http.routers.whoami-iamon99-http.middlewares=whoami-iamon99-https'
      - 'traefik.http.middlewares.whoami-iamon99-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.whoami-iamon99-https.rule=Host(`whoami.iamon99.com`)'
      - 'traefik.http.routers.whoami-iamon99-https.entrypoints=websecure'
      - 'traefik.http.routers.whoami-iamon99-https.tls.certresolver=myresolver'
    # depends_on:
    #   - traefik

  whoami-louislabs:
    image: 'traefik/whoami'
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-louislabs-http.rule=Host(`whoami.louislabs.com`)'
      - 'traefik.http.routers.whoami-louislabs-http.entrypoints=web'
      - 'traefik.http.routers.whoami-louislabs-http.middlewares=whoami-louislabs-https'
      - 'traefik.http.middlewares.whoami-louislabs-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.whoami-louislabs-https.rule=Host(`whoami.louislabs.com`)'
      - 'traefik.http.routers.whoami-louislabs-https.entrypoints=websecure'
      - 'traefik.http.routers.whoami-louislabs-https.tls.certresolver=myresolver'
    # depends_on:
    #   - traefik

networks:
  default:
    external:
      name: traefik-proxy-network
