version: '2'
services:
  traefik:
    image: traefik:1.5.2
    command: --web --docker --docker.domain=iamon99.com --log.filePath=/logs/traefik.log --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - ./volumes:/logs
    labels:
      - 'traefik.enable=false'
  whoami:
    image: emilevauge/whoami
    labels:
      - 'traefik.backend=whoami'
      - 'traefik.frontend.rule=Host:node_helloworld.iamon99.com'
